# Generated by Django 4.1.5 on 2023-01-11 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='title')),
                ('scheme', models.CharField(choices=[('http', 'Http'), ('https', 'Https')], default='https', max_length=10, verbose_name='scheme')),
                ('host', models.URLField(db_index=True, max_length=255, verbose_name='host')),
                ('port', models.PositiveIntegerField(blank=True, null=True, verbose_name='port')),
            ],
            options={
                'verbose_name': 'server',
                'verbose_name_plural': 'servers',
                'ordering': ['title', 'host'],
            },
        ),
        migrations.CreateModel(
            name='ServerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='title')),
                ('path', models.CharField(blank=True, db_index=True, default='/', max_length=1023, verbose_name='relative path')),
                ('status', models.IntegerField(db_index=True, default=0, verbose_name='status')),
                ('last_ping_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='ping.server', verbose_name='server')),
            ],
            options={
                'verbose_name': 'server path',
                'verbose_name_plural': 'server paths',
                'ordering': ['server', 'path'],
                'unique_together': {('server', 'path')},
            },
        ),
    ]
